services:
  main-server:
    image: ghcr.io/auto-trading-temp-name/main-server:master
    restart: always
    ports:
      - 80:80
    networks:
      - auto-trading
    depends_on:
      - redis
      - algorithm-server
  algorithm-server:
    image: ghcr.io/auto-trading-temp-name/algorithm-server:transaction-service
    hostname: algorithm-server
    restart: always
    ports:
      - 5000:80
    networks:
      - auto-trading
    depends_on:
      - redis
      - price-collector
  price-collector:
    image: ghcr.io/auto-trading-temp-name/price-collector:master
    hostname: price-collector
    restart: always
    ports:
      - 6000:80
    networks:
      - auto-trading
    depends_on:
      - redis
  transactions:
    image: ghcr.io/auto-trading-temp-name/transactions:master
    restart: always
    networks:
      - auto-trading
    depends_on:
      - algorithm-server
      - price-collector
  plot-bot:
    image: ghcr.io/auto-trading-temp-name/plot-bot:master
    restart: always
    depends_on:
      - algorithm-server
  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    hostname: redis
    networks:
      - auto-trading
    volumes:
      - redis-store:/data
networks:
  auto-trading:
volumes:
  redis-store:
